import { Geist, Geist_Mono } from "next/font/google";
import "@/frontend/styles/globals.css";
import AsciiBackground from "@/frontend/components/AsciiBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AsciiBackground opacity={0.18} blur={0} scale={1.05} drift />
        {children}
      </body>
    </html>
  );
}
